version: "3.9"

services:
  db:
    image: postgres:16
    container_name: prisma-enum-during-migration-bug-db
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
